# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160504203919 on 2016-06-02 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(verbose_name=b'date published')),
                ('author_name', models.CharField(max_length=50)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninepy.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media', models.ImageField(upload_to=b'ninepy/')),
                ('publication_date', models.DateTimeField(verbose_name=b'date published')),
                ('author_name', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninepy.Post'),
        ),
    ]
